pipeline{
    agent {
        docker {
            image 'node:alpine3.12'
        }
    }
    stages{
        stage("Verificación"){
            steps{
                sh '''
                  node --version
                  npm version
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }
    }
    stage("construir"){
        steps{
            dir ('./03-docker/solution'){
                sh '''
                    npm instal
                    npm run build 
                '''
            }
        }    
    }
    stage('Unit test'){
            steps{
                dir('./03-docker/solution'){                
                    sh 'npm test'
                }
            } 
            
    }
}