pipeline{
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this release candidate?')
    }
    environment{
        VERSION = sh([script: 'cd 02-pipelines/solution && npx -c \'echo $npm_package_version\'', returnStdout: true ]).trim()
        VERSION_RC = 'rc.2'
    }
    stages{
        stage('Audit tools'){
            steps{
                auditTools()
            }
        } 
        stage('Build'){
            environment {
                VERSION_SUFFIX = getVersionSuffix()
            }
            steps{
                dir('./02-pipelines/solution'){ 
                    echo "Build verison ${VERSION} witch suffix: ${VERSION_SUFFIX}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit test'){
            steps{
                dir('./02-pipelines/solution'){                
                    sh 'npm test'
                }
            } 
            
        }
        stage('Publish') {
            when {
                expression { return params.RC }
            }
            steps {
                archiveArtifacts('02-pipelines/solution/app/')
            }
        }
    }
}

String getVersionSuffix() {
    if (params.RC) {
        return env.VERSION_RC + '+ci' + env.BUILD_NUMBER
    }  else {
        return env.VERSION_RC
       }
}

void auditTools() {
    sh '''
        git version
        docker version
        node --version
        npm version
    '''
}