def image

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'pwd' // Imprime el directorio de trabajo
                     sh 'ls -la ..' // Para ver el contenido del directorio padre (03-docker)
                     sh 'ls -la'    // Para ver el contenido del directorio actual (03-docker-1.3)
                     sh 'ls -la ../03-docker' // Ver el contenido de ../03-docker
                    image = docker.build("molmo/jenkins-pipeline-demos:0.0.1", "--pull -f solution/Dockerfile solution")
                }
            }          

        }
        stage('Push') {
            steps {
                script {
                    withDockerRegistry([credentialsId: "docker-hub", url: ""]) {
                        image.push()
                    }
                }
            }
        }
    }
}