pipeline{
    agent any 

    environment{
        VERSION = sh([script: 'cd 02-pipelines/solution && npx -c \'echo $npm_package_version\'', returnStdout: true ]).trim()
        VERSION_RC = 'rc.2'
    }
    stages{
        stage('Audit tools'){
            steps{
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
            }
        } 
        stage('Build'){
            steps{
                dir('./02-pipelines/solution') 
                echo "Build verison ${VERSION} witch suffix: ${VERSION_RC}"
                sh '''
                    npm install
                    npm run build
                '''
            }
        }
        stage('Unit test'){
            steps{
                dir('./02-pipelines/solution')
                sh 'npm test'
            } 
            
        }
    }
}